### PR TITLE
fix: passing command names in autocomplete decorator

### PR DESCRIPTION
**Pull request by V3ntus**
## About
This fixes autocomplete when passing command names in the decorator
- Adheres to scope specific commands
- Properly handles incorrect choice population

---

## Usage:
```py
@bot.command(
	...
    options=[interactions.Option(
        type=interactions.OptionType.STRING,
        name="topic",
        description="Test autocomplete",
        autocomplete=True  # define a command option used for autocomplete
    )]
)
async def test_command(ctx, topic: str = ""):
	...
	
# define an autocomplete callback
@bot.autocomplete(command="test", name="topic")
async def do_autocomplete(ctx, topic: str = ""):
    await ctx.populate([
        interactions.Choice(
            name="One",
            value="one"
        ),
        interactions.Choice(
            name="Two",
            value="two"
        )
    ])
```

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by V3ntus** [comment]
~~Todo: figure out why the return from `get_application_commands` is inconsistent with defined commands, and how to get a consistent response from the Discord API~~

Passing a guild ID in `get_application_commands` will fix. Without passing an ID, this defaults to global commands in the API when I was wanting commands in a scope, thus the inconsistency.

**Comment by mAxYoLo01** [comment]
Ok so this has fixed some previous issues, however when disable_sync = True, the autocomplete fails:
```python
Traceback (most recent call last):
  File "*\launch.py", line 57, in <module>
    @bot.autocomplete("cog", "load")
  File "*\interactions\client.py", line 616, in autocomplete
    application_id=self.me.id, guild_id=_command_obj.guild_id
AttributeError: 'NoneType' object has no attribute 'guild_id'
```

Would switching the `name` and `command` arguments of the autocomplete function make more sense? To go from general -> option

**Comment by V3ntus** [comment]
> Ok so this has fixed some previous issues, however when disable_sync = True, the autocomplete fails:

Ah I had a hunch this would break. Will look into it

> Would switching the `name` and `command` arguments of the autocomplete function make more sense? To go from general -> option

Oh yes, I agree. I'll switch them over

**Comment by mAxYoLo01** [comment]
Can confirm everything works on my side, **LGTM!**

File: interactions/client.py [hunk 1]
```diff
@@ -579,8 +586,34 @@ def decorator(coro: Coroutine) -> Any:
...
+    @staticmethod
+    def _find_command(commands: List, command: str) -> ApplicationCommand:
+        """
+        Iterates over commands and returns an ApplicationCommand if it matches the name from command
+
+        :ivar commands: The list of dicts to iterate through
+        :type commands: List[ApplicationCommand]
+        :ivar command: The name of the command to match:
+        :type command: str
+        """
```
Comment (FayeDel) [inline interactions/client.py]: Add a `:return` and `:rtype` to documentation that states that this will return an `ApplicationCommand`

File: interactions/client.py [hunk 2]
```diff
@@ -579,8 +586,34 @@ def decorator(coro: Coroutine) -> Any:
 
         return decorator
 
+    @staticmethod
+    def _find_command(commands: List, command: str) -> ApplicationCommand:
```
Comment (FayeDel) [inline interactions/client.py]: Rename the typehint from `List` to `List[Dict]`
(to match consistency with the associated `.pyi` file.

File: interactions/client.py [hunk 3]
```diff
@@ -579,8 +586,34 @@ def decorator(coro: Coroutine) -> Any:
...
+        """
+        Iterates over commands and returns an ApplicationCommand if it matches the name from command
+
+        :ivar commands: The list of dicts to iterate through
+        :type commands: List[ApplicationCommand]
```
Comment (FayeDel) [inline interactions/client.py]: Documentation mismatch with input args, same change as the typehint change above ^

Comment (i0bs) [reply interactions/client.py]: Additionally, please use either \`\` or :class:\`\` formatting on L592.

File: interactions/client.py [hunk 4]
```diff
@@ -589,7 +589,7 @@ def decorator(coro: Coroutine) -> Any:
     @staticmethod
     def _find_command(commands: List[Dict], command: str) -> ApplicationCommand:
         """
-        Iterates over commands and returns an ApplicationCommand if it matches the name from command
+        Iterates over `commands` and returns an :class: ``ApplicationCommand`` if it matches the name from `command`
```
Comment (V3ntus) [inline interactions/client.py]: Is this appropriate RST usage?

**Comment by V3ntus** [comment]
`pre-commit` returning green here too, nothing to commit

**Comment by i0bs** [comment]
I'll move forward with merging this, `pre-commit` passed green on my end and the CI job for windows is specifically broken for the time being.

File: interactions/client.py [hunk 5]
```diff
@@ -627,8 +634,36 @@ def decorator(coro: Coroutine) -> Any:
 
         return decorator
 
+    @staticmethod
+    def _find_command(commands: List[Dict], command: str) -> ApplicationCommand:
+        """
+        Iterates over `commands` and returns an :class: ``ApplicationCommand`` if it matches the name from `command`
```
Comment (i0bs) [inline interactions/client.py]:
```suggestion
        Iterates over `commands` and returns an :class:`ApplicationCommand` if it matches the name from `command`
```

**Review by i0bs — CHANGES_REQUESTED** [review]

**Review by i0bs — APPROVED** [review]
