### PR TITLE
fix: add member's _client for message reactions

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

This pull request adds `_client` to the member attribute of a reaction object

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [ ] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves #
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Damego** [comment]
Why you don't use `add_client=True` in the `field`?

File: interactions/api/models/gw.py [hunk 1]
```diff
@@ -796,6 +796,9 @@ class MessageReaction(DictSerializerMixin):
     member: Optional[Member] = field(converter=Member, default=None)
     emoji: Optional[Emoji] = field(converter=Emoji, default=None)
 
+    def __attrs_post_init__(self):
+        self.member._client = self._client
```
Comment (Damego) [inline interactions/api/models/gw.py]: discord doesn't send `member` data in `message_reaction_remove` event so it will raise error `An error occurred dispatching message_reaction_remove: 'NoneType' object has no attribute '_client'`.
Use `add_client=True`

**Review by Damego — CHANGES_REQUESTED** [review]

File: interactions/api/models/gw.py (hunk 1 above)
Comment (sillyElvy) [reply interactions/api/models/gw.py]: Done, didnt know it exists

**Review by Damego — APPROVED** [review]

**Review by Catalyst4222 — APPROVED** [review]
