### PR TITLE
fix💥: don't pass kwargs to modal callbacks

### LINKED ISSUE #1517: [BUG] modal_callback
### Library Version

5.8.0

### Describe the Bug

When using the @component_callback I seem to be getting an error related to the ID or Custom ID of an InputText field.

### Minimal Reproducible Code

```python
from interactions import Client, InputText, Modal, SlashContext, TextStyles, modal_callback, slash_command

bot = Client()


@slash_command(name="trigger_modal")
async def trigger_modal(ctx: SlashContext):
    modal = Modal(
        InputText(
            style=TextStyles.PARAGRAPH,
            label="URL (glitchii or discohook)",
            required=True,
            min_length=5,
        ),
        title="Embed Builder",
        custom_id="embed_builder_modal",
    )
    await ctx.send_modal(modal)


@modal_callback("embed_builder_modal")
async def embed_builder_modal(ctx: SlashContext):
    await ctx.send("this is placeholder text")


bot.start("token")
```

### Traceback

```[2023-08-07 05:07:40] [ERROR   ] Ignoring exception in Modal Callback for custom_id embed_builder_modal:
Traceback (most recent call last):
  File "/home/aiden/tfc-bot/.venv/lib/python3.11/site-packages/interactions/client/client.py", line 1890, in __dispatch_interaction
    response = await callback
               ^^^^^^^^^^^^^^
  File "/home/aiden/tfc-bot/.venv/lib/python3.11/site-packages/interactions/models/internal/command.py", line 132, in __call__
    await self.call_callback(self.callback, context)
  File "/home/aiden/tfc-bot/.venv/lib/python3.11/site-packages/interactions/models/internal/command.py", line 198, in call_callback
    await self.call_with_binding(callback, context, **context.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aiden/tfc-bot/.venv/lib/python3.11/site-packages/interactions/models/internal/callback.py", line 43, in call_with_binding
    return await callback(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: EmbedBuilder.embed_builder_modal() got an unexpected keyword argument 'bb430638-9361-464d-b570-f4304e2f25d7'
```

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AstreaTSS**
## Pull Request Type

- [ ] Feature addition
- [x] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
This PR fixes #1517 by making sure `ctx.kwargs` is not passed into modal callbacks. While this behavior was unintended, this change is breaking, hence the draft status.

## Changes
- Override `call_callback` in `ModalCommand` so that the actual callback does not receive `**ctx.kwargs`.

## Related Issues
Fixes #1517.

## Test Scenarios
See bug report.

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [ ] I've updated / added  documentation, where applicable

### CODE REVIEW

**Comment by AstreaTSS** [comment]
Closing as #1619 supersedes this as a non-breaking change. That being said, this should be done at some time.
