### PR TITLE
fixing sub_command cmd part

### PR DESCRIPTION
**Pull request by dennis0324**
## About

This pull request is about fixing sub_commands part , which was `second_option:str` to `second_option:str = ""`

before code show error `TypeError: run.<locals>.cmd() missing 1 required positional argument: 'second_option'` so add "" to fix the code

## Checklist

- [ ] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- [ ] I've made this pull request for/as: (check all that apply)
  - [x] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [ ] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Target unstable branch please
