### PR TITLE
fix: Set the websocket's token without referencing the httpclient

### PR DESCRIPTION
**Pull request by Catalyst4222**
## About

This pull request fixes `AttributeError: 'str' object has no attribute '_req'`

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues) (If existent):.
  - resolves: an issue [presented on Discord](https://canary.discord.com/channels/789032594456576001/876490879815254097/1013737202959794248)
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

File: interactions/api/gateway/client.py [hunk 1]
```diff
@@ -149,7 +149,7 @@ def __init__(
             "timeout": 60,
             "autoclose": False,
             "compress": 0,
-            "headers": {"User-Agent": self._http._req._headers["User-Agent"]},
```
Comment (Damego) [inline interactions/api/gateway/client.py:152]: `self._http._req._headers["User-Agent"]` is not token

image

**Review by sillyElvy — CHANGES_REQUESTED** [review]
What damego said

File: interactions/api/gateway/client.py (hunk 1 above)
Comment (Catalyst4222) [reply interactions/api/gateway/client.py:152]: Changed, thank you for pointing that out

**Review by sillyElvy — APPROVED** [review]
