### PR TITLE
Fix!: prevent ``NoneType`` error during sub command checks and add kwarg for sub_commands without options

### LINKED ISSUE #569: Subcommand not passing to command function [BUG]
### Describe the bug.

I was trying to create a slash function that has two subcommands, which each take no options. However, when the slash command's subcommand is run, even though the subcommand is passed via JSON, it is not passed to the sub_command argument of the command function.

However, if the subcommand has an option, it works fine and both the subcommand and the option are passed to the command function.

function decorator of the command in question:
```py
@bot.command(
    name="opt",
    description="Opts in or out of the Twitter starboard",
    scope=575336474333937670,
    options=[
        interactions.Option(
            name="in",
            description="Opts in to the Twitter starboard",
            type=interactions.OptionType.SUB_COMMAND,
            options=[],
        ),
        interactions.Option(
            name="out",
            description="Opts out of the Twitter starboard",
            type=interactions.OptionType.SUB_COMMAND,
            options=[],
        ),
    ],
)
```

### List the steps.

1. Create a command that has a subcommand that takes no options
2. Run the code and try to run the subcommand in a server.

### What you expected.

The subcommand should have executed when run, which in this case, it is supposed to pull the first entry from a MariaDB database and send it into the channel.

### What you saw.

On discord, after the command was run, the standard "this application did not respond" notice and the program exits with a non-zero exit code.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "/Users/-/Desktop/yes-yes-bot/main.py", line 106, in <module>
    bot.start()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 109, in start
    self._loop.run_until_complete(self._ready())
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 307, in _ready
    await self._login()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 312, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 209, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 277, in _handle_connection
    self._dispatch_event(event, data)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 381, in _dispatch_event
    self._dispatch.dispatch(_name, *__args, **__kwargs)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/dispatch.py", line 37, in dispatch
    self.loop.create_task(event(*args, **kwargs))
TypeError: opt() missing 1 required positional argument: 'sub_command'
```

however, logging tells me that it was passed via JSON
```
[*fragment of the json*]

'data': {'type': 1, 'options': [{'type': 1, 'options': [], 'name': 'out'}], 'name': 'opt', 'id': '946668308533510145'}, 'channel_id': '694159911071776808', 'application_id': '946662687755091989'}
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

### LINKED ISSUE #575: [BUG] Slash command with "Attachment" option type gives an error
### Describe the bug.

When trying to accept an attachment argument in a slash command, the library gives an error:
`AttributeError: 'Attachment' object has no attribute '_client'`

### List the steps.

Example test script

```python
import interactions

if __name__ == "__main__":
    bot = interactions.Client(token="YOUR_TOKEN_HERE")
    
    @bot.command(
        name="attach",
        description="Some description",
        scope=YOUR_SCOPE_HERE,
        options= [
            interactions.Option(
                name="image",
                description="Attached image",
                type=interactions.OptionType.ATTACHMENT,
                required=True
            )
        ]
    )
    async def attach(ctx: interactions.CommandContext, image: interactions.Attachment):
        await ctx.send("Success")

    bot.start()
```

### What you expected.

I expected the bot to reply with "Success".

### What you saw.

Instead, I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "................/test.py", line 23, in <module>
    bot.start()
  File "................/python3.9/site-packages/interactions/client.py", line 109, in start
    self._loop.run_until_complete(self._ready())
  File "................/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "................/python3.9/site-packages/interactions/client.py", line 307, in _ready
    await self._login()
  File "................/python3.9/site-packages/interactions/client.py", line 312, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 209, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 277, in _handle_connection
    self._dispatch_event(event, data)
  File "................/python3.9/site-packages/interactions/api/gateway.py", line 340, in _dispatch_event
    _type[option.value]._client = self._http
AttributeError: 'Attachment' object has no attribute '_client'
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

### PR DESCRIPTION
**Pull request by sillyElvy**
## About

See https://discord.com/channels/789032594456576001/946655656092524584/946655661213749249

also fixes an error where sub_command would not be dispatched if it had no options

also adds _client to the Attachment object to prevent an AttributeError

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): #569 #575
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by V3ntus** [comment]
LGTM (tested against options bug)

**Review by FayeDel — APPROVED** [review]
