### PR TITLE
fix: falsey arguments not getting passed to kwargs

### LINKED ISSUE #570: Falsey data not getting passed to context [BUG]
### Describe the bug.

When running a slash command, if an argument is falsey (e.g. an empty string, or the integer 0), it causes the argument to not get passed to the command function, which causes a TypeError because the required positional argument is not given.

### List the steps.

1. Create a slash command as per usual that takes in an Integer option.
2. Run the script.
3. Run the command and pass in 0.

### What you expected.

The argument should have been passed to the function.

### What you saw.

Instead, it isn't passed to the function and I received this traceback error given from my Python terminal:
```
Traceback (most recent call last):
  File "/Users/-/Desktop/yes-yes-bot/main.py", line 129, in <module>
    bot.start()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 109, in start
    self._loop.run_until_complete(self._ready())
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 307, in _ready
    await self._login()
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/client.py", line 312, in _login
    await self._websocket._establish_connection(self._shard, self._presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 209, in _establish_connection
    await self._handle_connection(stream, shard, presence)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 277, in _handle_connection
    self._dispatch_event(event, data)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/gateway.py", line 381, in _dispatch_event
    self._dispatch.dispatch(_name, *__args, **__kwargs)
  File "/Users/-/.pyenv/versions/3.9.9/lib/python3.9/site-packages/interactions/api/dispatch.py", line 37, in dispatch
    self.loop.create_task(event(*args, **kwargs))
TypeError: opt() missing 1 required positional argument: 'mode'
```

### What version of the library did you use?

release

### Code of Conduct

- [X] I agree to follow the contribution requirements.

### PR DESCRIPTION
**Pull request by peaceknight05**
## About

Fixes the boolean expression in gateway.py to only check for NoneType and not just falsey expressions.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): #570 
- [ ] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Review by i0bs — APPROVED** [review]
Thanks for catching this, we were trying to provide a sound refactor especially for aggregating the subcommand contextual derivation and seems we forget to consider conditions with false-y values.

**Comment by i0bs** [comment]
FYI, there is a merge conflict, this will be automatically merged upon correction.

**Comment by i0bs** [comment]
This PR currently has merge conflicts, and will be automatically merged upon resolution.

**Comment by i0bs** [comment]
This PR will be closed in 1 week following this message if the changes requested, as well as the resolution of merge conflicts are not met.

**Comment by sillyElvy** [comment]
Closing; merge conflicts have not been resolved
