### PR TITLE
fix: emoji deletion error on guild leave

### PR DESCRIPTION
**Pull request by Speedcup**
## About

Fixes the following error whenever the bot leaves a guild:
```
File "interactions\client\smart_cache.py", line 642, in delete_guild
    if emoji._guild_id == guild_id:  # noqa
       ^^^^^^^^^^^^^^^
AttributeError: 'Snowflake' object has no attribute '_guild_id'
```

## Checklist

- [ ] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.
- [ ] I have added the `versionadded`, `versionchanged` and `deprecated` to any new or changed user-facing function I committed.

### Pull-Request specification

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [ ] To add a new feature
  - [ ] As a general enhancement
  - [ ] As a refactor of the library/the library's code
  - [x] To fix an existing bug
  - [ ] To resolve #ISSUENUMBER

### CODE REVIEW

**Review by Damego — APPROVED** [review]

File: interactions/models/internal/context.py [hunk 1]
```diff
@@ -598,7 +598,9 @@ async def defer(self, *, ephemeral: bool = False, edit_origin: bool = False) ->
             raise RuntimeError("Interaction has already been responded to.")
 
         payload = {
-            "type": CallbackType.DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE if not edit_origin else CallbackType.DEFERRED_UPDATE_MESSAGE
+            "type": CallbackType.DEFERRED_CHANNEL_MESSAGE_WITH_SOURCE
```
Comment (LordOfPolls) [inline interactions/models/internal/context.py:601]: This does not appear related to what you are trying to resolve - please rebase your pr before it can be merged

Comment (Speedcup) [reply interactions/models/internal/context.py:601]: This aint my change, this has been automatically formatted by pre-commit-ci[

Comment (LordOfPolls) [reply interactions/models/internal/context.py:601]: Okeydoke, ill ignore it then
