### PR TITLE
Refactor: change logging level to warning for not dispatchable events

### PR DESCRIPTION
**Pull request by athyk**
## About

This pull request changes .fatal to .warning. This allows suppression if you have non existent functions to handle these events.

Before:
```
CRITICAL:gateway:An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
CRITICAL:gateway:An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
```

After:
```
WARNING:gateway:An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
WARNING:gateway:An error occured dispatching voice_state_update: module 'interactions' has no attribute 'VoiceState'
```

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Review by sillyElvy — CHANGES_REQUESTED** [review]
Please use a convenientonal commit scope and pr title

**Comment by Damego** [comment]
Also change branch to `unstable`

**Review by sillyElvy — APPROVED** [review]

**Comment by sillyElvy** [comment]
Thanks for contributing!
