### PR TITLE
fix: cannot provide Client.intents as list

### LINKED ISSUE #442: [BUG] Cannot specify intents as a list
**Describe the bug**

When `intents` is passed as a list to `Client`, it is appended to without initialization.

**Reproducing steps**

Reproduction code:

```py
from interactions import Client, Intents

bot = Client(
    token='TOKEN',
    intents=[Intents.GUILDS, Intents.GUILD_MEMBERS],
)

bot.start()
```

**Expected behavior**
Intent number is computed from the list.

**What actually happened**
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\snaz\Documents\dpy-int-test\bot.py", line 4, in <module>
    bot = Client(
  File "C:\Users\snaz\AppData\Local\pypoetry\Cache\virtualenvs\dpy-int-test-coV1hBcm-py3.10\lib\site-packages\interactions\client.py", line 64, in __init__
    self.intents |= intent
AttributeError: 'Client' object has no attribute 'intents'
```

**Root cause**
When intents is a list, the code tries to repeatedly binary-or all passed intent numbers without initializing the variable first.

**Versions**
Reproduced on `4.0.1`, `stable`, and `unstable`.

- [ ] I am using discord.py versions 1.7 and below with my code.
    - [ ] I am using 2.0 or higher, or a modified fork.
- [ ] I am using dis-snek with my code.
- [x] I am not using any of the listed above and am using the library code alone.

### PR DESCRIPTION
**Pull request by snazzyfox**
## About

Fixes bug where intents provided as a list causes error.

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [x] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent): Fixes #442 
- [x] I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by i0bs** [comment]
I've decided to move over to singular `Intents` for the time being. In order to build the intents, you'll need to use the `|` operator.
