### PR TITLE
fix: `client`, `command` and `extension` are missed in `on_command`

### LINKED ISSUE #1133: [BUG] Context is missing `command` attribute in the `on_component` event
### Describe the bug.

Taken from [`#AttributeError 'NoneType' object has no attribute 'name'`](https://canary.discord.com/channels/789032594456576001/1033886778165305424/1033886778165305424) in the help forum

In the `on_command` event, there is a possibility that `ctx.command` is None instead of the associated Command instance. This is due to a race condition where some attribute processing for Context is done when the command is being invoked. This issue likely applies to other attributes as well, though that has not been tested yet

A workaround is to call `asyncio.sleep` with a short delay, but users likely won't find that solution on their own

### List the steps.

Set up the client with a command and a listener for the `on_command` event. In the event, access `ctx.command`

### What you expected.

`ctx.command` to be a Command instance 

### What you saw.

`ctx.command` is None

### What version of the library did you use?

release

### Version specification

4.3.2

### Code of Conduct

- [X] I agree to follow the contribution requirements.

### PR DESCRIPTION
**Pull request by Damego**
## About

This pull request moves `on_command` event dispatching to other place where command's func is called. Resolves #1133 

## Checklist

- [ ] The ``pre-commit`` code linter has been run over all edited files to ensure the code is linted.
- [x] I've ensured the change(s) work on `3.8.6` and higher.
- [ ] I have added the `versionadded`, `versionchanged` and `deprecated` to any new or changed user-facing function I committed.

### Pull-Request specification

I've made this pull request: (check all that apply)
  - [ ] For the documentation
  - [ ] To add a new feature
  - [ ] As a general enhancement
  - [x] As a refactor of the library/the library's code
  - [x] To fix an existing bug
  - [x] To resolve #1133 

This is:
  - [ ] A breaking change

### CODE REVIEW

File: interactions/client/models/command.py [hunk 1]
```diff
@@ -897,6 +897,8 @@ async def wrapper(ctx: "CommandContext", *args, **kwargs):
             ctx.command = self
             ctx.extension = self.extension
 
+            self.listener.dispatch("on_command", ctx)
```
Comment (Toricane) [inline interactions/client/models/command.py:900]: Is it better to dispatch `on_command` before the command is executed or after?

Comment (Damego) [reply interactions/client/models/command.py:900]: I put dispatch before calling a command function. Can't after because we are raising an error

Comment (i0bs) [reply interactions/client/models/command.py:900]: @Toricane We should probably be dispatching beforehand anyhow, so that developers can have that data exposed to them before a potential error is thrown

Comment (Damego) [reply interactions/client/models/command.py:900]: Isn't what I did?

**Review by i0bs — APPROVED** [review]
