### ISSUE TITLE
[BUG] If an autocomplete function is a method of a Client subclass, the object binding is missing.

### ISSUE THREAD

**Issue by fractal13** [interactions-py/interactions.py#1582]
### Library Version

5.11.0

### Describe the Bug

Autocomplete functions implemented as methods of a Client subclass are not called with binding to the client object. This causes the autocomplete call to raise an exception.

### Steps to Reproduce

The attached bot will demonstrate the failure when the user tries to issue the command: /ichart c4
[autocomplete-failure.zip](https://github.com/interactions-py/interactions.py/files/13518373/autocomplete-failure.zip)

### Expected Results

I would expect to have a method of the Client class be usable as an autocomplete routine.

### Minimal Reproducible Code

```python
I'm sorry it's so long, but please see the attached bot in the Steps to Reproduce.
```

### Traceback

$ ./bot6-autocomplete-fails.py
This bot is owned by @fractal13
Task exception was never retrieved
future: <Task finished name='Task-56' coro=<Client._dispatch_interaction() done, defined at /home/cgl/repos/interactions.py/interactions/client/client.py:1773> exception=TypeError("MyBot.chart_c4_integer_autocomplete() missing 1 required positional argument: 'ctx'")>
Traceback (most recent call last):
  File "/home/cgl/repos/interactions.py/interactions/client/client.py", line 1818, in _dispatch_interaction
    callback=callback(ctx),
TypeError: MyBot.chart_c4_integer_autocomplete() missing 1 required positional argument: 'ctx'

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

I have a PR that fixes this issue. There may be a better way to fix it. Please feel free to use your own solution.

**Comment by LordOfPolls** [comment]
Please don't use zips for minimal reproducibles - it's incredible bad practice and a security concern for the person downloading it. 

Please just share the relevant code - if you can't do that, just the relevant file

**Comment by fractal13** [comment]
Thanks for letting me know. The UI won't let me upload a .py file. So, here's the file contents:

#!/usr/bin/env python3
from interactions import Client, Intents, listen
from interactions import slash_command, SlashContext, SlashCommand
from interactions import OptionType, slash_option, SlashCommandChoice
from interactions import AutocompleteContext
import os

class MyBot(Client):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        return

    @listen()
    async def on_ready(self):
        print(f"This bot is owned by {bot.owner}")

    @slash_command(name="ichart", description="Autocomplete failure example")
    async def chart(self, ctx: SlashContext):
        await ctx.send("chart")
    
    @chart.subcommand(sub_cmd_name="c4", sub_cmd_description="one integer from auto complete list, required.")
    @slash_option(
        name="integer_option",
        description="Integer Option",
        required=True,
        opt_type=OptionType.INTEGER,
        autocomplete=True)
    async def chart_c4(self, ctx: SlashContext, integer_option: int):
        await ctx.send(f"You input {integer_option}")

    @chart_c4.autocomplete("integer_option")
    async def chart_c4_integer_autocomplete(self, ctx: AutocompleteContext):
        string_option_input = ctx.input_text  # can be empty

        choices = []
        if len(string_option_input) < 3:
            for i in (1, 2, 3):
                entry = { "name": f"{string_option_input}{i}", "value": f"{string_option_input}{i}" }
                choices.append(entry)
        else:
            entry = { "name": f"{string_option_input}", "value": f"{string_option_input}" }
            choices.append(entry)
        await ctx.send(choices)


def build_bot():
    bot = MyBot(intents=Intents.DEFAULT)
    return bot

bot = build_bot()
bot.start(os.environ["TOKEN"])

**Comment by eightween** [comment]
This likely came from a fault in our documentation, `self` is not required to be passed into the argument signature for `chart_c4` *or* `chart_c4_integer_autocomplete`.

**Comment by AstreaTSS** [comment]
What? No, this is a valid bug. The binding should be set here.

**Comment by AstreaTSS** [comment]
To clarify, this doesn't fit in with the behavior of the rest of our features. Usually `self` *is* accounted for when using client subclasses, and so autocomplete should too.

**Comment by eightween** [comment]
> To clarify, this doesn't fit in with the behavior of the rest of our features.

Neither [autocomplete](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#autocomplete-more-than-25-choices-needed) or [subcommand](https://interactions-py.github.io/interactions.py/Guides/03%20Creating%20Commands/#subcommands) guides require `self`, I have no idea what you're talking about.

> Usually `self` _is_ accounted for when using client subclasses, and so autocomplete should too.

They are explicitly passing `self` when the first positional we expect for dispatching context is `ctx` itself. Are you sure we're required to actually pass it?

**Comment by AstreaTSS** [comment]
The guides don't require `self` because they assume you're making the commands *outside* of a subclass in the main file where the bot is. This is a reasonable assumption for beginners who haven't used extensions or subclasses of `Client`.

However, interactions.py has always supported making a command inside of a bot subclass. Try it out yourself using `self` and all - it'll work just fine, as intended (you can dig into the code to find this, but it's there). The fact that autocomplete doesn't work like making a command and so doesn't pass in `self` is an exception, hence it being a bug.

**Comment by eightween** [comment]
This was a bad pass-over on my part, thanks for the callout @AstreaTSS. I'll be appropriately changing labels on the issue.

**Comment by eightween** [comment]
Resolved by #1583
