### PR TITLE
feat: add moderated for create_tag methods

### LINKED ISSUE #1591: [BUG] Moderated argument missing for tags
### Library Version

5.11.0

### Describe the Bug

While creating a new tag for a forum you can set the moderation value for it. 

image

image
https://discord.com/developers/docs/resources/channel#forum-tag-object-forum-tag-structure

### Steps to Reproduce

Try to create a mod only tag for a forum channel.

### Expected Results

That you can make the tag mod only

### Minimal Reproducible Code

_No response_

### Traceback

_No response_

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

_No response_

### LINKED ISSUE #1592: [FEAT] Add create_invite method to GuildForum
### Library Version

5.11.0

### Describe the Bug

`AttributeError: 'GuildForum' object has no attribute 'create_invite'`
image

### Steps to Reproduce

Try creating an invitation for a forum channel.

### Expected Results

That you can create one.

### Minimal Reproducible Code

_No response_

### Traceback

_No response_

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.
- [X] I have attempted to debug this myself, and I believe this issue is with the library

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by AstreaTSS**
## Pull Request Type

- [x] Feature addition
- [ ] Bugfix
- [ ] Documentation update
- [ ] Code refactor
- [ ] Tests improvement
- [ ] CI/CD pipeline enhancement
- [ ] Other: [Replace with a description]

## Description
Adds in the `moderated` field for the `create_tag` methods. This was already in `ThreadTag`, but some other places missed this.

## Changes
See description.

## Related Issues
Fixes #1591

## Test Scenarios
```python
await forum.create_tag("tag", "👋", moderated=True)
```

## Python Compatibility

- [ ] I've ensured my code works on Python `3.10.x`
- [x] I've ensured my code works on Python `3.11.x`

## Checklist

- [x] I've run the `pre-commit` code linter over all edited files
- [x] I've tested my changes on supported Python versions
- [ ] I've added tests for my code, if applicable
- [x] I've updated / added  documentation, where applicable

### CODE REVIEW

**Review by FayeDel — APPROVED** [review]
LGTM 👍🏻

File: interactions/api/http/http_requests/channels.py [hunk 1]
```diff
@@ -585,6 +585,7 @@ async def create_tag(
         name: str,
         emoji_id: Optional["Snowflake_Type"] = None,
         emoji_name: Optional[str] = None,
+        moderated: bool = False,
```
Comment (eightween) [inline interactions/api/http/http_requests/channels.py:588]: Same as #1608

**Review by eightween — APPROVED** [review]

**Review by silasary — APPROVED** [review]
