### PR TITLE
fix: fix some bugs with cache

### PR DESCRIPTION
**Pull request by Damego**
## About

This pull request fixes these bugs:
- `An error occured dispatching channel_update: 'NoneType' object has no attribute 'id'`
- `on_message_update(before, after)` before always is None When you edit a message which not in cache
- Wrong getting id of models

## Checklist

- [x] I've ran `pre-commit` to format and lint the change(s) made.
- [x] I've checked to make sure the change(s) work on `3.8.6` and higher.
- [ ] This fixes/solves an [Issue](https://github.com/goverfl0w/discord-interactions/issues).
  - (If existent):
- I've made this pull request for/as: (check all that apply)
  - [ ] Documentation
  - [ ] Breaking change
  - [ ] New feature/enhancement
  - [x] Bugfix

### CODE REVIEW

**Comment by Damego** [comment]
Draft until I test everything

File: interactions/api/gateway/client.py [hunk 1]
```diff
@@ -409,30 +409,27 @@ def _dispatch_event(self, event: str, data: dict) -> None:
...
+                    elif model.__name__.startswith("Guild"):
+                        model_name = model.__name__[5:]
+                        if _data := getattr(obj, model_name, None):
+                            id = (
+                                getattr(_data, "id")
+                                if not isinstance(_data, dict)
+                                else Snowflake(_data["id"])
+                            )
+                        elif hasattr(obj, f"{model_name}_id"):
+                            id = getattr(obj, f"{model_name}_id")
```
Comment (sillyElvy) [inline interactions/api/gateway/client.py]:
```suggestion
                            id = getattr(obj, f"{model_name}_id", None)
```

File: interactions/api/models/gw.py [hunk 2]
```diff
@@ -780,9 +780,9 @@ class MessageReaction(DictSerializerMixin):
     emoji: Optional[Emoji] = field(converter=Emoji, default=None)
 
 
-class ReactionRemove(MessageReaction):
+class MessageReactionRemove(MessageReaction):
```
Comment (sillyElvy) [inline interactions/api/models/gw.py:783]: Does this still work with all events?

**Review by sillyElvy — CHANGES_REQUESTED** [review]

File: interactions/api/models/gw.py (hunk 2 above)
Comment (Damego) [reply interactions/api/models/gw.py:783]: I tested all reaction events so yeah thats works

File: interactions/api/gateway/client.py [hunk 3]
```diff
@@ -450,18 +447,15 @@ def __modify_guild_cache():
...
                                 _obj.append(obj)
-
                             for index, __obj in enumerate(_obj):
                                 if __obj.id == id:
                                     if "_remove" in name or "_delete" in name:
                                         _obj.remove(__obj)
 
                                     elif "_update" in name and hasattr(obj, "id"):
-                                        _obj[index] = _data
+                                        _obj[index] = obj
```
Comment (sillyElvy) [inline interactions/api/gateway/client.py:458]: ^Can you explain this changes?

**Review by sillyElvy — CHANGES_REQUESTED** [review]

File: interactions/api/gateway/client.py (hunk 3 above)
Comment (Damego) [reply interactions/api/gateway/client.py:458]: `_data` is None because you tries to get `"Channel"` from channel instanse.
Then in `guild.channels` instead of normal channel appears `None` and then you get error when edit channel

image

Comment (sillyElvy) [reply interactions/api/gateway/client.py:458]: I see

**Review by sillyElvy — APPROVED** [review]
if it works, LGTM!

**Comment by Damego** [comment]
~~I will test it more tommorow. I wanna sleep~~

**Comment by Damego** [comment]
I didn't get any error so we can merge it ig
